services: 
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - 8080:8080
  cli:
    build:
      context: .
      dockerfile: cli/Dockerfile
    depends_on:
      - api