services: 
  prime-service:
    build:
      context: .
      dockerfile: PrimeService/Dockerfile
    ports:
      - 8080:8080
  cli:
    build:
      context: .
      dockerfile: cli/Dockerfile
    depends_on:
      - prime-service